#version 430 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

writeonly layout(rgba8, binding = 0) uniform image2D ping_im;

uniform float elapsed_time;

void main() {
    ivec2 image_coord = ivec2(gl_GlobalInvocationID.xy);
    float r = sin(elapsed_time*5.0) * 0.5 + 0.5;
    float g = cos(elapsed_time*2.0) * 0.5 + 0.5;
    imageStore(ping_im, image_coord, vec4(r, g, 0.1, 1.0));
}


